Repository DeveloperAcademy-POSTECH/MC3-Team9-NineToOne, pull requests merged in 2022-07, with the labels that each got.

#2 feat: Create Project
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  GaNaDa/GaNaDa.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GaNaDa/GaNaDa/AppDelegate.swift
  GaNaDa/GaNaDa/Assets.xcassets/AccentColor.colorset/Contents.json
  GaNaDa/GaNaDa/Assets.xcassets/AppIcon.appiconset/Contents.json
  GaNaDa/GaNaDa/Assets.xcassets/Contents.json
  GaNaDa/GaNaDa/Base.lproj/LaunchScreen.storyboard
  GaNaDa/GaNaDa/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/Info.plist
  GaNaDa/GaNaDa/SceneDelegate.swift
  GaNaDa/GaNaDa/ViewController.swift
  GaNaDa/GaNaDaTests/GaNaDaTests.swift
  GaNaDa/GaNaDaUITests/GaNaDaUITests.swift
  GaNaDa/GaNaDaUITests/GaNaDaUITestsLaunchTests.swift
Labels: feature

#4 resource: #3, #5, #6, #7 Project File Organizing
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/App/AppDelegate.swift
  GaNaDa/GaNaDa/App/Base.lproj/LaunchScreen.storyboard
  GaNaDa/GaNaDa/App/Info.plist
  GaNaDa/GaNaDa/App/SceneDelegate.swift
  GaNaDa/GaNaDa/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Contents.json
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/ViewController.swift
Labels: resource

#21 feat: customColor,Font를 UI Extension에 추가
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/App/Info.plist
  GaNaDa/GaNaDa/Extension/UIColor+Extension.swift
  GaNaDa/GaNaDa/Extension/UIFont+Extension.swift
  GaNaDa/GaNaDa/Resource/Font/NanumPen.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-Black.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-Bold.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-ExtraBold.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-ExtraLight.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-Light.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-Medium.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-Regular.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-SemiBold.otf
  GaNaDa/GaNaDa/Resource/Font/Pretendard-Thin.otf
Labels: feature

#27 Feat/quiz type1
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/View/TodayQuiz/Quiz.swift
  GaNaDa/GaNaDa/View/TodayQuiz/QuizType1.swift
  GaNaDa/GaNaDa/View/TodayQuiz/QuizType1.xib
Labels: feature

#28 Feat/quiz second view
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/Extension/UIColor+Extension.swift
  GaNaDa/GaNaDa/UIKitPreviewExtension.swift
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/History/HistoryCollectionView.swift
  GaNaDa/GaNaDa/View/History/HistoryViewController.swift
  GaNaDa/GaNaDa/View/History/ViewComponents/QuizType2CollectionViewCell.swift
Labels: feature

#36 [Feat]: todayQuiz collectionView 추가
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/Model/Quiz.swift
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/TodayQuiz/QuizTypeBlank.swift
  GaNaDa/GaNaDa/View/TodayQuiz/QuizTypeBlank.xib
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature

#37 Feat/history collection view
  GaNaDa/GaNaDa/View/History/HistoryCollectionView.swift
  GaNaDa/GaNaDa/View/History/HistoryViewController.swift
  GaNaDa/GaNaDa/View/History/ViewComponents/QuizType2CollectionViewCell.swift
Labels: feature

#42 [feat]: #40 문제 풀이 페이지 UI 설정
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GaNaDa/GaNaDa/App/Base.lproj/LaunchScreen.storyboard
  GaNaDa/GaNaDa/Extension/UIColor+Extension.swift
  GaNaDa/GaNaDa/Extension/UIViewController+Extension.swift
  GaNaDa/GaNaDa/Model/Quiz.swift
  GaNaDa/GaNaDa/Resource/Assets/LaunchScreen.xcassets/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/LaunchScreen.xcassets/LaunchScreen.imageset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/LaunchScreen.xcassets/LaunchScreen.imageset/LaunchScreen.svg
  GaNaDa/GaNaDa/Resource/Assets/LaunchScreen.xcassets/LaunchScreenBackground.imageset/Artboard 2.svg
  GaNaDa/GaNaDa/Resource/Assets/LaunchScreen.xcassets/LaunchScreenBackground.imageset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/LaunchScreen.xcassets/TempTitleLogo.imageset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/LaunchScreen.xcassets/TempTitleLogo.imageset/TempTitleLogo.svg
  GaNaDa/GaNaDa/Resource/Firework.json
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/QuizDetail/QuizAnswerViewController.swift
  GaNaDa/GaNaDa/View/QuizDetail/QuizViewController.swift
Labels: feature

#45 [fea] : 컬러에셋 추가 & 바로 사용할 수 있도록 코드 추가
  GaNaDa/GaNaDa/Extension/UIColor+Extension.swift
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Color/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Color/black.colorset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Color/customIvory.colorset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Color/customOrange.colorset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Color/darkGray.colorset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Color/lightGray.colorset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/Color/point.colorset/Contents.json
Labels: resource

#43 [feat]: #22 오늘의 퀴즈 페이지 유저 정보 가져오기
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizViewController.swift
Labels: feature

#46 [feat]: #23 해설 뷰 레이아웃 생성
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/QuizDetail/QuizDetailViewController.swift
Labels: feature

#50 [Chore]: Modify ProgressView's Color
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizViewController.swift
Labels: chore

#56 [feat] 선택지를 랜덤으로 섞기
  GaNaDa/GaNaDa/Model/Quiz.swift
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/QuizDetail/QuizViewController.swift
Labels: feature

#58 [Feat]: Add function tapToHome
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/QuizDetail/QuizDetailViewController.swift
Labels: feature

#61 [Feat]: Add Changing user icon function
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature

#64 feat: #63 View 합치기
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/App/Info.plist
  GaNaDa/GaNaDa/Extension/UIActivityIndicatorView+Extension.swift
  GaNaDa/GaNaDa/Extension/UIViewController+Extension.swift
  GaNaDa/GaNaDa/Extension/UIWindow+Extension.swift
  GaNaDa/GaNaDa/Manager/NetworkManager.swift
  GaNaDa/GaNaDa/Manager/NetworkService.swift
  GaNaDa/GaNaDa/Model/Quiz.swift
  GaNaDa/GaNaDa/Model/QuizDTO.swift
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/History/HistoryViewController.swift
  GaNaDa/GaNaDa/View/QuizDetail/QuizAnswerViewController.swift
  GaNaDa/GaNaDa/View/QuizDetail/QuizDetailViewController.swift
  GaNaDa/GaNaDa/View/QuizDetail/QuizViewController.swift
  GaNaDa/GaNaDa/View/Setting/SettingViewController.swift
  GaNaDa/GaNaDa/View/Setting/UserLevelViewController.swift
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature

#65 Feat/solved quiz type2 cell
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/Extension/CALayer+Extension.swift
  GaNaDa/GaNaDa/Extension/UILabel+Extension.swift
  GaNaDa/GaNaDa/Model/HistoryQuiz.swift
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/right.imageset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/right.imageset/right.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/wrong.imageset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/wrong.imageset/wrong.png
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/History/HistoryViewController.swift
  GaNaDa/GaNaDa/View/History/ViewComponents/QuizCollectionViewCell.swift
  GaNaDa/GaNaDa/View/History/ViewComponents/QuizType2CollectionViewCell.swift
  GaNaDa/GaNaDa/View/History/ViewComponents/SolvedQuizType1CollectionViewCell.swift
  GaNaDa/GaNaDa/View/History/ViewComponents/SolvedQuizType1CollectionViewCell.xib
  GaNaDa/GaNaDa/View/History/ViewComponents/SolvedQuizType2CollectionViewCell.swift
  GaNaDa/GaNaDa/View/History/ViewComponents/SolvedQuizType2CollectionViewCell.xib
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature
