Repository DeveloperAcademy-POSTECH/MC3-Team9-NineToOne, pull requests merged in 2022-08, with the labels that each got.

#66 feat: #63 작업사항 합치기
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/QuizDetail/QuizAnswerViewController.swift
  GaNaDa/GaNaDa/View/QuizDetail/QuizDetailViewController.swift
  GaNaDa/GaNaDa/View/QuizDetail/QuizViewController.swift
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature

#70 Rey/setting
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/Manager/UserDefaultManager.swift
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/chevron.imageset/Contents.json
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/chevron.imageset/chevron.svg
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/QuizDetail/QuizAnswerViewController.swift
  GaNaDa/GaNaDa/View/Setting/SettingViewController.swift
  GaNaDa/GaNaDa/View/Setting/UserLevelViewController.swift
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature

#72 feat : 오늘의 퀴즈에서 푼 문제 적용시키기
  GaNaDa/GaNaDa/View/History/ViewComponents/SolvedQuizType1CollectionViewCell.xib
  GaNaDa/GaNaDa/View/History/ViewComponents/SolvedQuizType2CollectionViewCell.xib
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature

#74 feat : 필터 ui 적용
  GaNaDa/GaNaDa/View/History/ViewComponents/FilteringButtonsView.swift
Labels: feature

#77 feat: 히스토리에서 맞춘 문제는 바로 해설로, 못 푼문제는 문제 풀이로 연결
  GaNaDa/GaNaDa/View/History/HistoryViewController.swift
Labels: feature

#80 feat: #75 SettingView in PushNotification
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
  GaNaDa/GaNaDa/App/AppDelegate.swift
  GaNaDa/GaNaDa/Manager/NotificationManager.swift
  GaNaDa/GaNaDa/View/Base.lproj/Main.storyboard
  GaNaDa/GaNaDa/View/Setting/SettingViewController.swift
Labels: feature

#85 feat: #75 Notification Center 구현
  GaNaDa/GaNaDa/App/AppDelegate.swift
  GaNaDa/GaNaDa/Manager/NotificationManager.swift
Labels: feature

#86 feat : border 적용 & 시간 리미트 해제
  GaNaDa/GaNaDa/View/TodayQuiz/TodayQuizCollectionVC.swift
Labels: feature

#93 Add App Icon
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/100.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/1024.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/114.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/120.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/128.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/144.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/152.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/16.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/167.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/172.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/180.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/196.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/20.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/216.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/256.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/29.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/32.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/40.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/48.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/50.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/512.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/55.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/57.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/58.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/60.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/64.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/72.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/76.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/80.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/87.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/88.png
  GaNaDa/GaNaDa/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: docs, feature

#95 Add App Name
  GaNaDa/GaNaDa.xcodeproj/project.pbxproj
Labels: docs
